{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.tlsSecretName }}"
  labels:
    app: {{ template "pulsar.name" . }}
    chart: {{ template "pulsar.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: "pulsar-tls"
    cluster: {{ template "pulsar.fullname" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.certificate | b64enc }}
  tls.key: {{ .Values.secrets.key | b64enc }}
  ca.crt: {{ .Values.secrets.caCertificate | b64enc }}
---
{{- end }}